# Generated by Django 5.2.14 on 2026-05-16 21:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField(unique=True)),
                ('ocupada', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('horario_entrada', models.DateTimeField(default=datetime.datetime.now)),
                ('horario_saida', models.DateTimeField(blank=True, null=True)),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('PIX', 'PIX'), ('DEBITO', 'Débito'), ('CREDITO', 'Crédito')], max_length=10, null=True)),
                ('ativa', models.BooleanField(default=True)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estacionamento.vaga')),
            ],
        ),
    ]
